### ISSUE TITLE
clarification on adding syntax definition files

### ISSUE THREAD

**Issue by uvtc** [jgm/skylighting#112]
Are the Kate syntax definition files drop-in compatible with skylighting?

Are upstream issues and PR's to be made at <https://github.com/KDE/syntax-highlighting> or <https://invent.kde.org/frameworks/syntax-highlighting>?

Do you know of any tools available to streamline creation of these syntax definition files?

On that KDE gitlab site, how does one go about creating a merge request?

**Comment by jgm** [comment]
> Are the Kate syntax definition files drop-in compatible with skylighting?

Yes.  They should be.  In a couple of cases there may be small incompatibilites, but these can be reported.  In any case, with a few exceptions (see the .patch files in skylighting-core/xml) we just use the xml files from the KDE repository.

If things aren't working properly, there are two possibilities:  (1) the xml syntax definition is flawed; (2) skylighting's interpretation of the definition is wrong.  One way to tell is to open the file in the Kate editor and see if it's properly highlighted there. If so, then we probably have (2) and it should be reported here. Otherwise, it's (1) and should be reported to KDE.

> On that KDE gitlab site, how does one go about creating a merge request?

There is some information in our README. That exhausts what I know.
