### ISSUE TITLE
Update syntax definition from upstream 

### ISSUE THREAD

**Issue by pablooliveira** [jgm/skylighting#15]
Hi,

Could you please update syntax definitions from upstream? In particular, could you please include the new definition for Tiger (https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/tiger.xml).

Thanks !

**Comment by jgm** [comment]
We don't include all the definitions by default, since
that would add a lot to compilation time and library size.
We try to include the most widely used ones.

In the case of tiger, I'm not sure...can you say a bit
about it?

Note that skylighting now allows dynamic loading of xml
defintiions (and so will pandoc starting with the upcoming
2.0).

+++ Pablo de Oliveira Castro [Aug 27 17 19:53 ]:

**Comment by pablooliveira** [comment]
Tiger is a simple language for teaching compiler courses introduced by A. Appel in his "Modern Compiler implementation in ML/C/Java" books. 

My use case was generating beamer slides with pandoc that contain snippets of tiger code. I'm currently using the git version of pandoc that supports dynamic loading of the xml definition.

Since it's a pretty rare use-case I agree it should not probably be included by default. Feel free to close this issue.
