### ISSUE TITLE
Dependency footprint

### ISSUE THREAD

**Issue by benjamin-hodgson** [jgm/skylighting#152]
`skylighting-core` has a few dependencies which are only used for certain output formats: `ansi-terminal`, `blaze-html`, etc. Would you be open to making those dependencies optional? Either via compilation flags or by extracting the formatting modules into separate packages.

**Comment by jgm** [comment]
No, not by compilation flags, because the API is not supposed to depend on cabal flags.

So it would have to be by splitting the rendering functions (Skylighting.Format) into a separate package.  I'm open to that suggestion, but (a) that would take a lot of my time, and it's not a high priority for me; and (b) this would be a breaking API change that might inconvenience other users.

**Comment by benjamin-hodgson** [comment]
Thanks for getting back so quickly!

One could do it in a non-breaking fashion, by leaving the formatting code in `skylighting-core` and extracting an "even more core" package containing everything except the formatting code. `skylighting -> skylighting-core -> skylighting-corer`. (Not saying that's a good design, just that it's doable!)

If the level of effort is the main issue here, I'm certainly prepared to help with that!

**Comment by jgm** [comment]
Can you say why the dependency issue footprint is so important to you?

**Comment by benjamin-hodgson** [comment]
Just the usual reasons: slows down initial build, inflates binary size, more to audit, potential for upstream security issues, potential for dependency solving problems. An app which doesn't write HTML shouldn't need `blaze` as a dependency.
