### ISSUE TITLE
Incorrectly recognizes PHP variable as keyword

### ISSUE THREAD

**Issue by ricpelo** [jgm/skylighting#30]
With this test case:

```markdown
Hello.

```php
$test = '1234';
echo $test;
    ```
```

after running `pandoc test.md -o test.html` I get the following output:

```html
<p>Hello.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode php"><code class="sourceCode php"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">$test</span> = <span class="st">&#39;1234&#39;</span><span class="ot">;</span></a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">echo</span> <span class="kw">$test</span><span class="ot">;</span></a></code></pre></div>
```

Both `$test` and `echo` goes into the same class `kw`, but IMHO `$test` should be recognized as *variable* instead of a keyword.

**Comment by jgm** [comment]
Take a look at the php.xml from which the parser is
generated.  It contains:

     <itemData name="Special Variable" defStyleNum="dsKeyword" color="#5555FF" selColor="#ffffff" bold="1" italic="0" spellChecking="false" />
      <itemData name="Variable" defStyleNum="dsKeyword" color="#5555FF" selColor="#ffffff" bold="0" italic="0" spellChecking="false" />

which tells it to use "Keyword" tokens for variables (with a
special color, which is ignored by skylighting).

So skylighting is working properly here. I can't comment on
the decision in the underlying KDE syntax definition file.

Note that you can now use custom xml definitions with
pandoc, so that might be a solution for you.

**Comment by ricpelo** [comment]
Thank you very much! Using a custom `php.xml` seems to be the best option.
