### ISSUE TITLE
Consider relicensing as LGPL?

### ISSUE THREAD

**Issue by jtdaugherty** [jgm/skylighting#34]
I'm curious about whether you'd be willing to release the next version of Skylighting under the LGPL instead of GPL-2 to ease use with applications that are released under other open licenses.

**Comment by jgm** [comment]
Since Haskell statically links libraries by default, the
distinction between GPL and LGPL usually doesn't matter.

But the real issue is that, since the parsers are derived
from xml syntax definitions from KDE, we must be GPL if any
of those syntax definitions are.  And a few of them are,
e.g. r.xml.

+++ Jonathan Daugherty [Jan 25 18 01:44 ]:

**Comment by jtdaugherty** [comment]
Okay, thanks for the clarification. It sounds like the key issue is that the XML files are being used to generate parsers; if the library just read in XML files at runtime, would it be able to avoid the GPL? (That's not a request, but I'm wanting to understand this better.)

**Comment by jgm** [comment]
+++ Jonathan Daugherty [Jan 25 18 10:30 ]:
>   Okay, thanks for the clarification. It sounds like the key issue is
>   that the XML files are being used to generate parsers; if the library
>   just read in XML files at runtime, would it be able to avoid the GPL?
>   (That's not a request, but I'm wanting to understand this better.)

Yes, I believe so, though I'm not a lawyer.  The relevant
concept is "derivative work."

**Comment by jtdaugherty** [comment]
Okay, thanks!
